<?php

namespace ContainerUYy1tbx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FvGJzCSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FvGJzCS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FvGJzCS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'restaurant' => ['privates', '.errored..service_locator.FvGJzCS.App\\Entity\\Restaurant', NULL, 'Cannot autowire service ".service_locator.FvGJzCS": it needs an instance of "App\\Entity\\Restaurant" but this type has been excluded in "config/services.yaml".'],
        ], [
            'restaurant' => 'App\\Entity\\Restaurant',
        ]);
    }
}
