<?php

namespace ContainerUYy1tbx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ErM1NGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.er_M1NG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.er_M1NG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.TFYbZQh', 'get_ServiceLocator_TFYbZQhService', true],
            'App\\Controller\\RestaurantController::editRestaurant' => ['privates', '.service_locator.FvGJzCS', 'get_ServiceLocator_FvGJzCSService', true],
            'App\\Controller\\RestaurantController::index' => ['privates', '.service_locator.XdnbiXt', 'get_ServiceLocator_XdnbiXtService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController::showDetails' => ['privates', '.service_locator.FvGJzCS', 'get_ServiceLocator_FvGJzCSService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.TFYbZQh', 'get_ServiceLocator_TFYbZQhService', true],
            'App\\Controller\\RestaurantController:editRestaurant' => ['privates', '.service_locator.FvGJzCS', 'get_ServiceLocator_FvGJzCSService', true],
            'App\\Controller\\RestaurantController:index' => ['privates', '.service_locator.XdnbiXt', 'get_ServiceLocator_XdnbiXtService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController:showDetails' => ['privates', '.service_locator.FvGJzCS', 'get_ServiceLocator_FvGJzCSService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RestaurantController::editRestaurant' => '?',
            'App\\Controller\\RestaurantController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::showDetails' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RestaurantController:editRestaurant' => '?',
            'App\\Controller\\RestaurantController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:showDetails' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
