<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUYy1tbx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUYy1tbx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUYy1tbx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUYy1tbx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUYy1tbx\App_KernelDevDebugContainer([
    'container.build_hash' => 'UYy1tbx',
    'container.build_id' => 'a1bfd1b1',
    'container.build_time' => 1709300551,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUYy1tbx');
