<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_reservation' => [[], ['_controller' => 'App\\Controller\\ReservationController::index'], [], [['text', '/reservation']], [], [], []],
    'restaurants' => [[], ['_controller' => 'App\\Controller\\RestaurantController::index'], [], [['text', '/restaurants']], [], [], []],
    'create_restaurant' => [[], ['_controller' => 'App\\Controller\\RestaurantController::createRestaurant'], [], [['text', '/create-restaurant']], [], [], []],
    'restaurant_edit' => [['id'], ['_controller' => 'App\\Controller\\RestaurantController::editRestaurant'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/edit-restaurant']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'restaurant_details' => [['id'], ['_controller' => 'App\\Controller\\SecurityController::showDetails'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/restaurant']], [], [], []],
    'welcome' => [[], ['_controller' => 'App\\Controller\\WelComeController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\RegistrationController::register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'App\Controller\ReservationController::index' => [[], ['_controller' => 'App\\Controller\\ReservationController::index'], [], [['text', '/reservation']], [], [], []],
    'App\Controller\RestaurantController::index' => [[], ['_controller' => 'App\\Controller\\RestaurantController::index'], [], [['text', '/restaurants']], [], [], []],
    'App\Controller\RestaurantController::createRestaurant' => [[], ['_controller' => 'App\\Controller\\RestaurantController::createRestaurant'], [], [['text', '/create-restaurant']], [], [], []],
    'App\Controller\RestaurantController::editRestaurant' => [['id'], ['_controller' => 'App\\Controller\\RestaurantController::editRestaurant'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/edit-restaurant']], [], [], []],
    'App\Controller\SecurityController::login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\SecurityController::logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'App\Controller\SecurityController::showDetails' => [['id'], ['_controller' => 'App\\Controller\\SecurityController::showDetails'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/restaurant']], [], [], []],
    'App\Controller\WelComeController::index' => [[], ['_controller' => 'App\\Controller\\WelComeController::index'], [], [['text', '/']], [], [], []],
];
